# Generated by Django 5.2.5 on 2025-10-22 21:19

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_missing_user_profile(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("core", "UserProfile")
    for user in User.objects.all():
        try:
            UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(user=user, access_level=2)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(0, 'VIEW'), (1, 'PERSONAL'), (2, 'FULL')], default=core.models.AccessLevel['PERSONAL'])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(populate_missing_user_profile, migrations.RunPython.noop),
    ]
