# Generated by Django 5.2.5 on 2025-09-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
